#!/usr/bin/env bash
set -e

CWD=`dirname "$0"`
RENDER="python3 $CWD/build_solana_templates.py"

PROGRAMS_FILE_PATH="$CWD/../src/apps/solana/transaction/programs.json"

FW_PATH="$CWD/../src/apps/solana/transaction"
FW_OUTPUT_PATH="$FW_PATH/instructions.py"

TESTS_PATH="$CWD/../../tests/device_tests/solana/construct"
TESTS_OUTPUT_PATH="$TESTS_PATH/instructions.py"

format() {
	isort $1 -q
	black $1 -q
	flake8 $1 -q
}

check_results() {
    TEMPLATE_PATH=$1
    OUTPUT_PATH=$2

    CHECK_FAIL=0
    TMP=`mktemp`
    TARGET=$OUTPUT_PATH
    $RENDER $TEMPLATE_PATH -p $PROGRAMS_FILE_PATH -o $TMP
    format $TMP

    if ! diff -u "$TARGET" "$TMP"; then
        CHECK_FAIL=1
    fi
    exit $CHECK_FAIL
}

if [ "$1" = "--check" ]; then
    check_results $FW_PATH $FW_OUTPUT_PATH
    check_results $TESTS_PATH $TESTS_OUTPUT_PATH
else
    $RENDER $FW_PATH -p $PROGRAMS_FILE_PATH -o $FW_OUTPUT_PATH
    format $FW_OUTPUT_PATH
    touch $FW_OUTPUT_PATH -r $PROGRAMS_FILE_PATH

    $RENDER $TESTS_PATH -p "$PROGRAMS_FILE_PATH" -o $TESTS_OUTPUT_PATH
    format $TESTS_OUTPUT_PATH
    touch $TESTS_OUTPUT_PATH -r $PROGRAMS_FILE_PATH
fi
