[package]
name = "cerberus-tjpgdec"
description = "Tiny JPEG Decompressor"
version = "0.1.0"
edition = "2021"
authors = ["Cerberus Company"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/Cerberus-Wallet/cerberus-firmware/"
